service:
  name: codemotion-2019
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-west-1
  environment:
    GHIBLI_URL: https://ghibliapi.herokuapp.com

functions:
  graphql:
    handler: handler.graphql
    events:
      - http:
          method: get
          path: graphql
      - http:
          method: post
          path: graphql
          cors: true